// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CCmUBHiYp1cjcJpMLJa7gxkb_XBAJGM',
    appId: '1:23316715809:web:2c10bfa05ea45b0cd2c660',
    messagingSenderId: '23316715809',
    projectId: 'health-4c6c4',
    authDomain: 'health-4c6c4.firebaseapp.com',
    storageBucket: 'health-4c6c4.appspot.com',
    measurementId: 'G-T3NKN32F92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2cJe6OuSCysQjtaj9mLwd7W39x1HyscU',
    appId: '1:23316715809:android:b9ba3988daaf1c4dd2c660',
    messagingSenderId: '23316715809',
    projectId: 'health-4c6c4',
    storageBucket: 'health-4c6c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCcdsQAl_gFnXS_RovSZj-oLz_7BPVsE',
    appId: '1:23316715809:ios:a5ef948b604986b6d2c660',
    messagingSenderId: '23316715809',
    projectId: 'health-4c6c4',
    storageBucket: 'health-4c6c4.appspot.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCcdsQAl_gFnXS_RovSZj-oLz_7BPVsE',
    appId: '1:23316715809:ios:a5ef948b604986b6d2c660',
    messagingSenderId: '23316715809',
    projectId: 'health-4c6c4',
    storageBucket: 'health-4c6c4.appspot.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8CCmUBHiYp1cjcJpMLJa7gxkb_XBAJGM',
    appId: '1:23316715809:web:312505ab1d1cdfbfd2c660',
    messagingSenderId: '23316715809',
    projectId: 'health-4c6c4',
    authDomain: 'health-4c6c4.firebaseapp.com',
    storageBucket: 'health-4c6c4.appspot.com',
    measurementId: 'G-1K2XT63ZZP',
  );
}
